apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- all.yaml
- hip-atomfeed-secrets.yml
- openmrs-otp-properties.yml
- openmrs-appt-properties.yml

configMapGenerator:
- name: health-check
  envs:
  - config.properties
generatorOptions:
  disableNameSuffixHash: true

patches:
- target:
    kind: Deployment
    name: "(clinic-config|openmrs)"
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: __ignored__
    spec:
      template:
        spec:
          serviceAccountName: status-checker
          initContainers:
            - name: preinit-check
              image: alpine:latest
              command: [ "/bin/sh", "-c"]
              args:
                - apk add postgresql-client kubectl &&
                  kubectl wait -l statefulset.kubernetes.io/pod-name=bahmni-"$ENV_CLINIC"-rabbitmq-0 --for=condition=ready pod -n "$ENV_CLINIC" --timeout=900s &&
                  kubectl wait -l statefulset.kubernetes.io/pod-name=bahmni-$ENV_CLINIC-postgresql-0 --for=condition=ready pod -n "$ENV_CLINIC" --timeout=900s &&
                  pg_isready -h bahmni-$ENV_CLINIC-postgresql
              envFrom:
                - configMapRef:
                    name: health-check
                    optional: false

- target:
    kind: Deployment
    name: "(bahmni-web|implementer-interface|patient-documents|appointments|bahmni-lab|reports)"
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: __ignored__
    spec:
      template:
        spec:
          serviceAccountName: status-checker
          initContainers:
            - name: preinit-check
              image: alpine:latest
              command: [ "/bin/sh", "-c"]
              args:
                - apk add postgresql-client kubectl curl &&
                  kubectl wait deployment/clinic-config --for=condition=available -n "$ENV_CLINIC" --timeout=900s &&
                  kubectl wait deployment/openmrs --for=condition=available -n "$ENV_CLINIC" --timeout=900s &&
                  while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://openmrs:8080/openmrs/)" != "200" ]]; do sleep 5; done
              envFrom:
                - configMapRef:
                    name: health-check
                    optional: false

- target:
    kind: Deployment
    name: "(bahmni-mart|bahmni-metabase|crater-atomfeed|crater-nginx|crater-php)"
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: __ignored__
    spec:
      template:
        spec:
          serviceAccountName: status-checker
          initContainers:
            - name: preinit-check
              image: alpine:latest
              command: [ "/bin/sh", "-c"]
              args:
                - apk add postgresql-client kubectl curl &&
                  kubectl wait deployment/bahmni-web --for=condition=available -n "$ENV_CLINIC" --timeout=900s &&
                  kubectl wait deployment/implementer-interface --for=condition=available -n "$ENV_CLINIC" --timeout=900s &&
                  kubectl wait deployment/patient-documents --for=condition=available -n "$ENV_CLINIC" --timeout=900s &&
                  kubectl wait deployment/appointments --for=condition=available -n "$ENV_CLINIC" --timeout=900s &&
                  kubectl wait deployment/bahmni-lab --for=condition=available -n "$ENV_CLINIC" --timeout=900s &&
                  kubectl wait deployment/reports --for=condition=available -n "$ENV_CLINIC" --timeout=900s
              envFrom:
                - configMapRef:
                    name: health-check
                    optional: false

- target:
    kind: Deployment
    name: "(abha-verification|hip|hip-atomfeed|hiu|hiu-ui|otp-service)"
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: __ignored__
    spec:
      template:
        spec:
          serviceAccountName: status-checker
          initContainers:
            - name: preinit-check
              image: alpine:latest
              command: [ "/bin/sh", "-c"]
              args:
                - apk add postgresql-client kubectl curl &&
                  kubectl wait deployment/bahmni-mart --for=condition=available -n "$ENV_CLINIC" --timeout=900s &&
                  kubectl wait deployment/bahmni-metabase --for=condition=available -n "$ENV_CLINIC" --timeout=900s &&
                  kubectl wait deployment/crater-atomfeed --for=condition=available -n "$ENV_CLINIC" --timeout=900s &&
                  kubectl wait deployment/crater-nginx --for=condition=available -n "$ENV_CLINIC" --timeout=900s &&
                  kubectl wait deployment/crater-php --for=condition=available -n "$ENV_CLINIC" --timeout=900s
              envFrom:
                - configMapRef:
                    name: health-check
                    optional: false

patchesStrategicMerge:
- crater-mail-secrets.yml
- openmrs-secrets.yml
- openmrs-config-map.yml
- hip-config-map.yml
- sms-config-map.yml
- crater-atomfeed-config-map.yml

- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: openmrs
  spec:
    template:
      spec:
        volumes:
          - name: openmrs-patient-images
            persistentVolumeClaim:
              claimName: openmrs-patient-images-pvc
          - name: openmrs-document-images
            persistentVolumeClaim:
              claimName: openmrs-document-images-pvc
          - name: openmrs-initializer-checksums
            persistentVolumeClaim:
              claimName: openmrs-initializer-checksums-pvc
          - name: openmrs-clinical-forms
            persistentVolumeClaim:
              claimName: openmrs-clinical-forms-pvc
          - name: bahmni-config
            persistentVolumeClaim:
              claimName: bahmni-config-pvc
          - name: bahmni-uploaded-results
            persistentVolumeClaim:
              claimName: bahmni-uploaded-results-pvc
          - name: bahmni-uploaded-files
            persistentVolumeClaim:
              claimName: bahmni-uploaded-files-pvc
          - name: openmrs-otp-properties
            secret:
              secretName: openmrs-otp-properties
          - name: openmrs-appt-properties
            secret:
              secretName: openmrs-appt-properties
        containers:
        - name: openmrs
          livenessProbe:
            httpGet:
              path: /openmrs/
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /openmrs/
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 40
          volumeMounts:
            - name: openmrs-patient-images
              mountPath: /home/bahmni/patient_images
            - name: openmrs-document-images
              mountPath: /home/bahmni/document_images
            - name: openmrs-initializer-checksums
              mountPath: /openmrs/data/configuration_checksums
            - name: openmrs-clinical-forms
              mountPath: /home/bahmni/clinical_forms
            - name: bahmni-config
              mountPath: /etc/bahmni_config
            - name: bahmni-uploaded-results
              mountPath: /home/bahmni/uploaded_results
            - name: bahmni-uploaded-files
              mountPath: /home/bahmni/uploaded-files
            - mountPath: "/openmrs/data/otp.properties"
              name: openmrs-otp-properties
              subPath: otp.properties
              readOnly: true
            - mountPath: "/openmrs/data/appt.properties"
              name: openmrs-appt-properties
              subPath: appt.properties
              readOnly: true

- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hip-atomfeed
  spec:
    template:
      spec:
        containers:
        - name: hip-atomfeed
          envFrom:
            - configMapRef:
                name: hip-atomfeed-config
                optional: false
            - secretRef:
                name: hip-atomfeed-secrets
                optional: false
